export const magicNumbers = {
  LOGIN: {
    MIN_LENGTH: 2,
    MAX_LENGTH: 24
  },
  LOGIN_OR_EMAIL: {
    MAX_LENGTH: 48
  },
  PASSWORD: {
    MIN_LENGTH: 4,
    MAX_LENGTH: 24
  },
  CODE: {
    MAX_LENGTH: 1,
    NUMBERS_LENGTH: 4
  },
  CAPTCHA: {
    NUMBERS_MIN_VALUE: 1,
    NUMBERS_MAX_VALUE: 10,
    NUMBERS_LENGTH: 4
  },
  TOPIC: {
    MIN_LENGTH: 16,
    MAX_LENGTH: 64
  },
  ONE_HUNDRED_TWENTY_MILLISECOND: 120,
  TWO_HUNDRED_MILLISECONDS: 200,
  FOUR_HUNDRED_MILLISECONDS: 400,
  ONE_THOUSAND_MILLISECONDS: 1000,
  ONE_THOUSAND_TWO_HUNDRED_MILLISECONDS: 1200,
  TEN_SECONDS: 10,
  SIXTY_SECONDS: 60,
  UNAUTHORIZED: 401
};
