export const magicNumbers = {
  MIN_USERNAME_LENGTH: 2,
  MAX_USERNAME_LENGTH: 24,
  MIN_PASSWORD_LENGTH: 4,
  MAX_PASSWORD_LENGTH: 24,
  TWO_HUNDRED_MILLISECONDS: 200,
  FOUR_HUNDRED_MILLISECONDS: 400,
  ONE_THOUSAND_TWO_HUNDRED_MILLISECONDS: 1200
};
