export const magicNumbers = {
  LOGIN: {
    MIN_LENGTH: 2,
    MAX_LENGTH: 24
  },
  PASSWORD: {
    MIN_LENGTH: 4,
    MAX_LENGTH: 24
  },
  TWO_HUNDRED_MILLISECONDS: 200,
  THREE_THOUSAND_MILLISECONDS: 3000,
  UNAUTHORIZED: 401
};
